@startuml

!include site-class.plantuml
!include tableau-user-class.plantuml


title The Workbook class


!startsub CLASSDESCRIPTION
class Workbook {
  -ID id
  -String name
  -String luid
  -String projectName
  -String description
  -String uri
  -String vizportalUrlId
  -DateTime createdAt
  -DateTime updatedAt
}
!endsub

Site -o Workbook : site
TableauUser --o Workbook : owner

@enduml
